---
# Don't forget to update deployment/whereabouts-chart/templates/reconciler.yaml as well
apiVersion: v1
kind: ConfigMap
metadata:
  name: whereabouts-config
  namespace: kube-system
data:
  cron-expression: "30 4 * * *"  # Default schedule is each day at 4:30am. Users may change this value to their liking.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whereabouts-reconciler
  namespace: kube-system
  labels:
    tier: node
    app: whereabouts-reconciler
spec:
  # replicas must not be set to more than 1
  # there is no leader election, so running multiple replicas would cause duplicate reconciliation.
  replicas: 1
  selector:
    matchLabels:
      app: whereabouts-reconciler
  template:
    metadata:
      labels:
        tier: node
        app: whereabouts-reconciler
        name: whereabouts-reconciler
    spec:
      serviceAccount: whereabouts
      serviceAccountName: whereabouts
      containers:
        - name: whereabouts-reconciler
          image: ghcr.io/k8snetworkplumbingwg/whereabouts:latest
          imagePullPolicy: Always
          command: ["/ip-reconciler"]
          args:
            - -log-level
            - debug
          env:
            - name: WHEREABOUTS_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 50Mi
          volumeMounts:
            - mountPath: /cron-schedule
              name: cron-scheduler-configmap
      volumes:
        - name: cron-scheduler-configmap
          configMap:
            name: whereabouts-config
            items:
              - key: cron-expression
                path: config
            defaultMode: 0744
