---
# Dont'forget to update deployment/whereabouts-chart/templates/daemonset.yaml as well
apiVersion: v1
kind: ServiceAccount
metadata:
  name: whereabouts
  namespace: kube-system
---
kind: ClusterRoleBinding
metadata:
  name: whereabouts
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: whereabouts-cni
subjects:
  - kind: ServiceAccount
    name: whereabouts
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: whereabouts-cni
rules:
  - apiGroups:
      - whereabouts.cni.cncf.io
    resources:
      - ippools
      - overlappingrangeipreservations
      - nodeslicepools
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "k8s.cni.cncf.io"
    resources:
      - network-attachment-definitions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
      - update
      - get
