apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- daemonset.yaml
- cni_role.yaml
images:
- name: controller
  newName: ghcr.io/k8snetworkplumbingwg/whereabouts
  newTag: latest
