# Manager deployment kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manager.yaml
images:
- name: controller
  newName: ghcr.io/k8snetworkplumbingwg/whereabouts
  newTag: latest
