---
apiVersion: v1
kind: ConfigMap
metadata:
  name: whereabouts-config
  namespace: {{ include "whereabouts.namespace" . }}
  labels:
    {{- include "whereabouts.labels" . | nindent 4 }}
data:
  cron-expression: {{ quote .Values.cronExpression }}
