# Dont'forget to update doc/crds/daemonset-install.yaml as well
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "whereabouts.fullname" . }}
  {{- include "whereabouts.namespace" . | nindent 2 }}
  labels:
    {{- include "whereabouts.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: whereabouts
      {{- include "whereabouts.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: {{ .Values.updateStrategy }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        name: whereabouts
        {{- include "whereabouts.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: true
      serviceAccountName: {{ include "whereabouts.serviceAccountName" . }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/bin/sh" ]
          args:
            - -c
            - |
              SLEEP=false source /install-cni.sh
              /token-watcher.sh &
              /ip-control-loop -log-level debug
          env:
          - name: NODENAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: WHEREABOUTS_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: cnibin
            mountPath: /host/opt/cni/bin
          - name: cni-net-dir
            mountPath: /host/etc/cni/net.d
          - name: cron-scheduler-configmap
            mountPath: /cron-schedule
      volumes:
        - name: cnibin
          hostPath:
            path: {{ .Values.cniConf.binDir }}
        - name: cni-net-dir
          hostPath:
            path: {{ .Values.cniConf.confDir }}
        - name: cron-scheduler-configmap
          configMap:
            name: {{ include "whereabouts.fullname" . }}-config
            defaultMode: 0744
            items:
            - key: "cron-expression"
              path: "config"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
