{{- if and .Values.operator.enabled (gt (int .Values.operator.replicas) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "whereabouts.fullname" . }}-operator
  {{- include "whereabouts.namespace" . | nindent 2 }}
  labels:
    {{- include "whereabouts.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ include "whereabouts.fullname" . }}-operator
{{- end }}
